### ISSUE TITLE
More domain suggestions

### ISSUE THREAD

**Issue by ngyikp** [avatsaev/mackeeper_blocker#9]
They like to shuffle their ad domains, so instead of directly blocking the domains, break their resources instead
```
static.mackeeper.com
static-site.mackeeper.com
cf.mackeeper.com
```

Download site:
```
download.mackeeper.com
```

From their website certificate, this may be a bit over the top though
```
kromtech.com
www.kromtech.com
kromtech.net
www.kromtech.net
mackeeper.co
www.mackeeper.co
getadwarebuster.com
www.getadwarebuster.com
mackeepersecurity.com
www.mackeepersecurity.com
trackmymac.com
www.trackmymac.com
```
<img width="541" alt="" src="https://cloud.githubusercontent.com/assets/6135313/25561586/324ee07c-2da2-11e7-8f46-2837b793f603.png">

**Comment by avatsaev** [comment]
Can you PR this one, I'll take care of #8 when I have time, thanks for the suggestions

**Comment by ngyikp** [comment]
Want all domains, or just the first two?

**Comment by avatsaev** [comment]
the first two will do
